export const GET_EMPLOYEE_COURSES = "GET_EMPLOYEE_COURSES";
export const GET_EMPLOYEE_COURSES_SUCCESS = "GET_EMPLOYEE_COURSES_SUCCESS";
export const GET_EMPLOYEE_COURSES_FAIL = "GET_EMPLOYEE_COURSES_FAIL";