export const GET_COURSE_STATISTICS = "GET_COURSE_STATISTICS";
export const GET_COURSE_STATISTICS_SUCCESS = "GET_COURSE_STATISTICS_SUCCESS";
export const GET_COURSE_STATISTICS_FAIL = "GET_COURSE_STATISTICS_FAIL";