export const GET_REQUIRED_COURSES = "GET_REQUIRED_COURSES";
export const GET_REQUIRED_COURSES_SUCCESS = "GET_REQUIRED_COURSES_SUCCESS";
export const GET_REQUIRED_COURSES_FAIL = "GET_REQUIRED_COURSES_FAIL";